### ISSUE TITLE
Line numbers are not grey

### ISSUE THREAD

**Issue by gizak** [RealGithub/RealGithub-VSCode#1]
VSCode: 1.2.1
Theme-RealGithub: 1.0.4

Mine's looks like this:

<img width="699" alt="screen shot 2016-06-27 at 10 44 53 am" src="https://cloud.githubusercontent.com/assets/2100512/16383784/7e4820a0-3c54-11e6-9f43-a49fbbcadc7d.png">

Everything is great except the line number column which is supposed to be grey. I found it's also cyan on Github Theme 0.0.2 as well. Any ideas how to fix it? Good work! I really like this theme!

**Comment by NoHomey** [comment]
Well this section Scope is named gutter\* and it seems like in VSCode it can't be changed from Color Theme, maybe it can with UI Theme, not sure but I can't do any thing about that bug. JSON keys are also light blue instead of dark, just can't fix it .... I'm going to leave this issue opened anyway for the future.

**Comment by NoHomey** [comment]
@gizak  v `1.0.5` has been released.
